# Generated by Django 5.0.1 on 2026-10-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dvc',
            new_name='dvh',
        ),
    ]
