# Generated by Django 5.0.1 on 2026-10-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0002_rename_dvc_dvh'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='company_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='mobile_number',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
