# Generated by Django 5.0.1 on 2026-10-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0003_dvh_company_name_dvh_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='digital_visiting_card',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='digital_visiting_card_flag',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
