# Generated by Django 5.0.1 on 2026-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0004_dvh_digital_visiting_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='google_review',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='google_review_flag',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
