# Generated by Django 5.0.1 on 2026-10-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0005_dvh_google_review_dvh_google_review_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='instgram',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='instgram_flag',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
