# Generated by Django 5.0.1 on 2026-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0006_dvh_instgram_dvh_instgram_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='facebook',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='facebook_flag',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
