# Generated by Django 5.0.1 on 2026-10-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0007_dvh_facebook_dvh_facebook_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='google_map',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='google_map_flag',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
