# Generated by Django 5.0.1 on 2026-10-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0008_dvh_google_map_dvh_google_map_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='website',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='website_flag',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
