# Generated by Django 5.0.1 on 2026-10-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0009_dvh_website_dvh_website_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvh',
            name='whatsapp',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvh',
            name='whatsapp_flag',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
