# Generated by Django 5.0.1 on 2026-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhubapp', '0010_dvh_whatsapp_dvh_whatsapp_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvh',
            name='google_review',
            field=models.TextField(),
        ),
    ]
