# Generated by Django 5.0.1 on 2026-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dvc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_flag', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=250)),
                ('designation_flag', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=250)),
                ('mobile_number_flag', models.CharField(max_length=250)),
                ('email_id', models.CharField(max_length=250)),
                ('email_id_flag', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('location_flag', models.CharField(max_length=250)),
                ('whatsapp_flag', models.CharField(max_length=250)),
                ('whatsapp', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('instagram_flag', models.CharField(max_length=250)),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
