# Generated by Django 5.0.1 on 2026-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='code',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
