# Generated by Django 5.0.1 on 2026-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0002_dvc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
