# Generated by Django 5.0.1 on 2026-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0003_dvc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='user_id',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
