# Generated by Django 5.0.1 on 2026-09-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0004_dvc_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvc',
            old_name='location',
            new_name='location_address',
        ),
        migrations.RenameField(
            model_name='dvc',
            old_name='location_flag',
            new_name='location_address_flag',
        ),
        migrations.AddField(
            model_name='dvc',
            name='location_url',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='location_url_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
