# Generated by Django 5.0.1 on 2026-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0005_rename_location_dvc_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='company_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='company_name_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
