# Generated by Django 5.0.1 on 2026-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0006_dvc_company_name_dvc_company_name_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='website_url',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='website_url_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
