# Generated by Django 5.0.1 on 2026-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0007_dvc_website_url_dvc_website_url_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='facebook',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='facebook_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
