# Generated by Django 5.0.1 on 2026-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0008_dvc_facebook_dvc_facebook_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='linkedin',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='linkedin_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
