# Generated by Django 5.0.1 on 2026-09-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0009_dvc_linkedin_dvc_linkedin_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='twitter',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='twitter_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
