# Generated by Django 5.0.1 on 2026-09-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0010_dvc_twitter_dvc_twitter_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='telegram',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='telegram_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
