# Generated by Django 5.0.1 on 2026-09-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvcapp', '0011_dvc_telegram_dvc_telegram_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvc',
            name='youtube',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvc',
            name='youtube_flag',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
