# Generated by Django 5.0.1 on 2026-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enduser_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('emp_description', models.TextField()),
                ('user_flage', models.IntegerField()),
            ],
        ),
    ]
