# Generated by Django 5.0.1 on 2026-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_enduser_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enduser_id',
            new_name='customer_id',
        ),
    ]
