# Generated by Django 5.0.1 on 2026-09-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_enduser_id_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduser_login',
            old_name='emp_description',
            new_name='customer_description',
        ),
        migrations.RenameField(
            model_name='enduser_login',
            old_name='user_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='enduser_login',
            old_name='name',
            new_name='customer_name',
        ),
    ]
