# Generated by Django 5.0.1 on 2026-09-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_emp_description_enduser_login_customer_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduser_login',
            old_name='user_flage',
            new_name='flag',
        ),
    ]
